# Base image
FROM node:alpine
# Working directory
WORKDIR /app
# Copy package.json for dependencies
COPY package.json .
# Install the dependencies
RUN npm install
# Copy the rest of the app files
COPY . .
#Run the application
CMD ["npm", "run", "start"]
